/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthSplatRouteImport } from './routes/auth.$'
import { Route as AppAdditionalRouteImport } from './routes/app.additional'
import { Route as WebhooksAppUninstalledRouteImport } from './routes/webhooks.app.uninstalled'
import { Route as WebhooksAppScopes_updateRouteImport } from './routes/webhooks.app.scopes_update'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSplatRoute = AuthSplatRouteImport.update({
  id: '/auth/$',
  path: '/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdditionalRoute = AppAdditionalRouteImport.update({
  id: '/additional',
  path: '/additional',
  getParentRoute: () => AppRoute,
} as any)
const WebhooksAppUninstalledRoute = WebhooksAppUninstalledRouteImport.update({
  id: '/webhooks/app/uninstalled',
  path: '/webhooks/app/uninstalled',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksAppScopes_updateRoute =
  WebhooksAppScopes_updateRouteImport.update({
    id: '/webhooks/app/scopes_update',
    path: '/webhooks/app/scopes_update',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/additional': typeof AppAdditionalRoute
  '/auth/$': typeof AuthSplatRoute
  '/auth/login': typeof AuthLoginRoute
  '/app/': typeof AppIndexRoute
  '/webhooks/app/scopes_update': typeof WebhooksAppScopes_updateRoute
  '/webhooks/app/uninstalled': typeof WebhooksAppUninstalledRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/additional': typeof AppAdditionalRoute
  '/auth/$': typeof AuthSplatRoute
  '/auth/login': typeof AuthLoginRoute
  '/app': typeof AppIndexRoute
  '/webhooks/app/scopes_update': typeof WebhooksAppScopes_updateRoute
  '/webhooks/app/uninstalled': typeof WebhooksAppUninstalledRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/additional': typeof AppAdditionalRoute
  '/auth/$': typeof AuthSplatRoute
  '/auth/login': typeof AuthLoginRoute
  '/app/': typeof AppIndexRoute
  '/webhooks/app/scopes_update': typeof WebhooksAppScopes_updateRoute
  '/webhooks/app/uninstalled': typeof WebhooksAppUninstalledRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/additional'
    | '/auth/$'
    | '/auth/login'
    | '/app/'
    | '/webhooks/app/scopes_update'
    | '/webhooks/app/uninstalled'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/additional'
    | '/auth/$'
    | '/auth/login'
    | '/app'
    | '/webhooks/app/scopes_update'
    | '/webhooks/app/uninstalled'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/additional'
    | '/auth/$'
    | '/auth/login'
    | '/app/'
    | '/webhooks/app/scopes_update'
    | '/webhooks/app/uninstalled'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthSplatRoute: typeof AuthSplatRoute
  AuthLoginRoute: typeof AuthLoginRoute
  WebhooksAppScopes_updateRoute: typeof WebhooksAppScopes_updateRoute
  WebhooksAppUninstalledRoute: typeof WebhooksAppUninstalledRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$': {
      id: '/auth/$'
      path: '/auth/$'
      fullPath: '/auth/$'
      preLoaderRoute: typeof AuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/additional': {
      id: '/app/additional'
      path: '/additional'
      fullPath: '/app/additional'
      preLoaderRoute: typeof AppAdditionalRouteImport
      parentRoute: typeof AppRoute
    }
    '/webhooks/app/uninstalled': {
      id: '/webhooks/app/uninstalled'
      path: '/webhooks/app/uninstalled'
      fullPath: '/webhooks/app/uninstalled'
      preLoaderRoute: typeof WebhooksAppUninstalledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/app/scopes_update': {
      id: '/webhooks/app/scopes_update'
      path: '/webhooks/app/scopes_update'
      fullPath: '/webhooks/app/scopes_update'
      preLoaderRoute: typeof WebhooksAppScopes_updateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdditionalRoute: typeof AppAdditionalRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdditionalRoute: AppAdditionalRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthSplatRoute: AuthSplatRoute,
  AuthLoginRoute: AuthLoginRoute,
  WebhooksAppScopes_updateRoute: WebhooksAppScopes_updateRoute,
  WebhooksAppUninstalledRoute: WebhooksAppUninstalledRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
